// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByRt7sgQXKoTBFPHGsXmqhhu3XlfLK_j4',
    appId: '1:212421823653:web:TEMPORARY',
    messagingSenderId: '212421823653',
    projectId: 'smartsplit-zanil',
    authDomain: 'smartsplit-zanil.firebaseapp.com',
    storageBucket: 'smartsplit-zanil.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByRt7sgQXKoTBFPHGsXmqhhu3XlfLK_j4',
    appId: '1:212421823653:android:c7923b19f4145b4a45914c',
    messagingSenderId: '212421823653',
    projectId: 'smartsplit-zanil',
    storageBucket: 'smartsplit-zanil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:PROJECT_NUMBER:ios:IOS_APP_ID',
    messagingSenderId: 'PROJECT_NUMBER',
    projectId: 'smartsplit-zanil',
    storageBucket: 'smartsplit-zanil.firebasestorage.app',
    iosBundleId: 'com.example.smartsplit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:PROJECT_NUMBER:macos:MACOS_APP_ID',
    messagingSenderId: 'PROJECT_NUMBER',
    projectId: 'smartsplit-zanil',
    storageBucket: 'smartsplit-zanil.firebasestorage.app',
    iosBundleId: 'com.example.smartsplit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: '1:PROJECT_NUMBER:windows:WINDOWS_APP_ID',
    messagingSenderId: 'PROJECT_NUMBER',
    projectId: 'smartsplit-zanil',
    storageBucket: 'smartsplit-zanil.firebasestorage.app',
  );
}
